name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Push to Nuget
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: ./Push.ps1
      shell: pwsh